name: install

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    # branches:
    #   - "**"
    # paths:
    #   - ".github/workflows/install.yml"
    #   - "assets/**"
    #   - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set_tag
        run: |
          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
          if [[ $tag != v* ]]; then
            tag=$(curl -sX GET "https://api.github.com/repos/${{ github.repository }}/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]')
            if [[ $tag != v* ]]; then
              tag="v0.0.0"
            fi
            tag=$(date "+$tag-%y%m%d-$(git rev-parse --short HEAD)")
          fi
          if ! $($is_release) ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            tag="$prefix-ci.$suffix"
          fi

          is_beta=false
          if [[ $tag =~ .*beta.* ]]; then
            is_beta=true
          fi

          is_alpha=false
          if [[ $tag =~ .*alpha.* ]]; then
            is_alpha=true
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT
          echo is_beta=$is_beta | tee -a $GITHUB_OUTPUT
          echo is_alpha=$is_alpha | tee -a $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_release: ${{ steps.set_tag.outputs.is_release }}
      is_beta: ${{ steps.set_tag.outputs.is_beta }}
      is_alpha: ${{ steps.set_tag.outputs.is_alpha }}

  install-win:
    needs: meta
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: windows-latest
          - arch: aarch64
            runner: windows-11-arm
      fail-fast: false
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-win-${{ matrix.arch }}*"
          tag: "v4.5.6"
          out-file-path: "deps"
          extract: true

      - name: Download MFAAvalonia
        id: download_mfa
        uses: robinraju/release-downloader@v1
        with:
          repository: SweetSmellFox/MFAAvalonia
          fileName: "MFAAvalonia-*-win-${{ (matrix.arch == 'x86_64' && 'x64') || (matrix.arch == 'aarch64' && 'arm64') }}*"
          tag: "v1.6.9"
          out-file-path: "MFA"
          extract: true

      - name: Clean up MFAAvalonia archive
        shell: bash
        run: |
          ARCHIVE_FILE_PATH="${{ fromJson(steps.download_mfa.outputs.downloaded_files)[0] }}"
          rm -f "${ARCHIVE_FILE_PATH}"
          echo "Archive cleanup command executed for MFAAvalonia."

      - name: Setup Embed Python
        shell: bash
        run: |
          python ci/setup_embed_python.py

      - name: Install Python dependencies
        shell: bash
        run: |
          ./install/python/python.exe -m pip install -r requirements.txt

      - name: Install
        shell: bash
        run: |
          ./install/python/python.exe ./ci/install.py ${{ needs.meta.outputs.tag }}
          if [ -d "MFA" ]; then
            echo "Copying MFA files to install directory..."
            mkdir -p install
            cp -rpvn MFA/. install/
          else
            echo "MFA directory not found, skipping copy."
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: MaaEOV-win-${{ matrix.arch }}
          path: "install"

  install-macos:
    needs: meta
    if: ${{ needs.meta.outputs.is_release == 'true' && needs.meta.outputs.is_beta != 'true' && needs.meta.outputs.is_alpha != 'true' }}
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: macos-15-intel
          - arch: aarch64
            runner: macos-latest
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-macos-${{ matrix.arch }}*"
          tag: "v4.5.6"
          out-file-path: "deps"
          extract: true

      - name: Download MFAAvalonia
        id: download_mfa
        uses: robinraju/release-downloader@v1
        with:
          repository: SweetSmellFox/MFAAvalonia
          fileName: "MFAAvalonia-*-osx-${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}*"
          tag: "v1.6.9"
          out-file-path: "MFA"
          extract: true

      - name: Clean up MFAAvalonia archive
        shell: bash
        run: |
          ARCHIVE_FILE_PATH="${{ fromJson(steps.download_mfa.outputs.downloaded_files)[0] }}"
          rm -f "${ARCHIVE_FILE_PATH}"
          echo "Archive cleanup command executed for MFAAvalonia."

      - name: Setup Embed Python
        shell: bash
        run: |
          python3 ci/setup_embed_python.py
          EMBED_PYTHON_PATH="./install/python/bin/python3"
          if [ -f "$EMBED_PYTHON_PATH" ]; then
            echo "Setting execute permission for $EMBED_PYTHON_PATH"
            chmod +x "$EMBED_PYTHON_PATH"
          else
            echo "Warning: Embedded Python executable not found at $EMBED_PYTHON_PATH. Skipping chmod."
          fi

      - name: Download Python dependencies
        shell: bash
        run: |
          ./install/python/bin/python3 -m pip install -r requirements.txt

      - name: Install
        shell: bash
        run: |
          ./install/python/bin/python3 ./ci/install.py ${{ needs.meta.outputs.tag }}
          if [ -d "MFA" ]; then
            echo "Copying MFA files to install directory..."
            mkdir -p install
            rsync -av --ignore-existing MFA/ install/
          else
            echo "MFA directory not found, skipping copy."
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: MaaEOV-macos-${{ matrix.arch }}
          path: "install"

  install-linux:
    needs: meta
    if: ${{ needs.meta.outputs.is_release == 'true' && needs.meta.outputs.is_beta != 'true' && needs.meta.outputs.is_alpha != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-linux-${{ matrix.arch }}*"
          tag: "v4.5.6"
          out-file-path: "deps"
          extract: true

      - name: Download MFAAvalonia
        id: download_mfa
        uses: robinraju/release-downloader@v1
        with:
          repository: SweetSmellFox/MFAAvalonia
          fileName: "MFAAvalonia-*-linux-${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}*"
          tag: "v1.6.9"
          out-file-path: "MFA"
          extract: true

      - name: Clean up MFAAvalonia archive
        shell: bash
        run: |
          ARCHIVE_FILE_PATH="${{ fromJson(steps.download_mfa.outputs.downloaded_files)[0] }}"
          rm -f "${ARCHIVE_FILE_PATH}"
          echo "Archive cleanup command executed for MFAAvalonia."

      - name: Install
        shell: bash
        run: |
          python ./ci/install.py ${{ needs.meta.outputs.tag }}
          if [ -d "MFA" ]; then
            echo "Copying MFA files to install directory..."
            mkdir -p install
            rsync -av --ignore-existing MFA/ install/
          else
            echo "MFA directory not found, skipping copy."
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: M9A-linux-${{ matrix.arch }}
          path: "install"

  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: .github/cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

  release:
    needs: [meta, install-win, install-macos, install-linux, changelog]
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: assets

      - run: |
          cd assets
          for f in *; do
            (cd $f && zip -r ../$f-${{ needs.meta.outputs.tag }}.zip .)
          done

      - uses: softprops/action-gh-release@v2.2.2
        with:
          files: assets/*
          tag_name: ${{ needs.meta.outputs.tag }}
          body: ${{ needs.changelog.outputs.release_body }}
          draft: ${{ needs.meta.outputs.is_alpha == 'true' }}
          prerelease: ${{ needs.meta.outputs.is_beta == 'true' }}